head:
  primer:
    analog_inputs:
      low: 0
      high: 8
    channel: 0
  quad1:
    analog_inputs:
      low: 1
      high: 9
    channel: 1
  quad2:
    analog_inputs:
      low: 2
      high: 10
    channel: 2
  quad3:
    analog_inputs:
      low: 3
      high: 11
    channel: 3
  quad4:
    analog_inputs:
      low: 4
      high: 12
    channel: 4
  quad5:
    analog_inputs:
      low: 5
      high: 13
    channel: 5
  quad6:
    analog_inputs:
      low: 6
      high: 14
    channel: 6
  system:
    channel: 7
manifold:
  c8:
    channel: 8
  c9:
    channel: 9
  c10:
    channel: 10
  c11:
    channel: 11
  c12:
    channel: 12
  c13:
    channel: 13
  c14:
    channel: 14
  c15:
    channel: 15
  c16:
    channel: 16
  c17:
    channel: 17
  c18:
    channel: 18
  c19:
    channel: 19
  c20:
    channel: 20
  aspirate:
    channel: 21
  seperate:
    channel: 22
setup_duration: 20
system_prime_count: 1
prime_duration: 10
prime_aspirate_duration: 15
fill_duration_full: 20
dispense_duration_full: 6
dispense_duration_on: 6
dispense_duration_off: 0
chemical_aspirate_duration: 40
chemical_separate_duration: 40
shake_speed_min: &shake_speed_min 200
shake_speed_max: &shake_speed_max 3000
aspirate_shake_speed: 200
separate_shake_speed: 200
inter_dispense_shake_speed: 400
inter_dispense_shake_duration: 10
shake_duration_min: 10
shake_attempts: 2
post_shake_off_duration: 5
adc_sample_count: 11
fill_duration_all_cylinders: 200
fill_duration_one_cylinder: 50
volume_crossover: 6
volume_max: 10
volume_threshold_initial: 1.0
pre_cylinder_fill_duration: 2
post_cylinder_fill_duration: 4
balance_zero_duration: 4
protocol:
- chemical: c8
  prime_count: 1
  dispense_volume: 10
  shake_speed: 200
  shake_duration: 0
  post_shake_duration: 0
  aspirate: true
  repeat: 1
- chemical: c9
  prime_count: 0
  dispense_volume: 10
  shake_speed: 200
  shake_duration: 0
  post_shake_duration: 0
  aspirate: true
  repeat: 1
- chemical: c10
  prime_count: 0
  dispense_volume: 10
  shake_speed: 200
  shake_duration: 0
  post_shake_duration: 0
  aspirate: true
  repeat: 1
- chemical: c11
  prime_count: 0
  dispense_volume: 10
  shake_speed: 200
  shake_duration: 0
  post_shake_duration: 0
  aspirate: true
  repeat: 1
- chemical: c20
  prime_count: 1
  dispense_volume: 10
  shake_speed: 200
  shake_duration: 0
  post_shake_duration: 0
  aspirate: true
  repeat: 1
