head:
  primer:
    analog_input: 0
    channel: 8
  quad1:
    analog_input: 1
    channel: 9
  quad2:
    analog_input: 2
    channel: 10
  quad3:
    analog_input: 3
    channel: 11
  quad4:
    analog_input: 4
    channel: 12
  quad5:
    analog_input: 5
    channel: 13
  quad6:
    analog_input: 6
    channel: 14
  system:
    channel: 15
manifold:
  bleach:
    channel: 16
  heptane:
    channel: 17
  pfa:
    channel: 18
  methanol:
    channel: 19
  block:
    channel: 20
  primary:
    channel: 21
  secondary:
    channel: 24
  pbt:
    channel: 28
  aspirate:
    channel: 29
  separate:
    channel: 30
setup_duration: 20
system_prime_count: 1
prime_duration: 10
prime_aspirate_duration: 15
load_duration: 6
dispense_duration: 6
chemical_aspirate_duration: 40
chemical_separate_duration: 40
shake_speed_min: &shake_speed_min 200
shake_speed_max: &shake_speed_max 3000
aspirate_shake_speed: 200
separate_shake_speed: 200
inter_dispense_shake_speed: 400
inter_dispense_shake_duration: 10
protocol:
- chemical: secondary
  prime_count: 2
  dispense_count: 0
  shake_speed: 0
  shake_duration: 0
  post_shake_duration: 0
  separate: false
  aspirate: false
  repeat: 0